### ISSUE TITLE
static/classes/classes.php getIP方法存在X-Forwarded-For头注入

### ISSUE THREAD

**Issue by Hacker-Kid** [EternalChampion61/officialsite#1]
在static/classes/classes.php中   
function getIP()
    {
        if (isset($_SERVER)) {
            if (isset($_SERVER["HTTP_X_FORWARDED_FOR"])) {
                return $_SERVER["HTTP_X_FORWARDED_FOR"];
            } else if (isset($_SERVER["HTTP_CLIENT_IP"])) {
                return $_SERVER["HTTP_CLIENT_IP"];
            } else {
                return $_SERVER["REMOTE_ADDR"];
            }
        } else {
            if (getenv("HTTP_X_FORWARDED_FOR")) {
                return getenv("HTTP_X_FORWARDED_FOR");
            } else if (getenv("HTTP_CLIENT_IP")) {
                return getenv("HTTP_CLIENT_IP");
            } else {
                return getenv("REMOTE_ADDR");
            }
        }
    }
此方法返回客户端ip,我们可以通过修改X-Forwarded-For头来控制这个方法的返回值,
此方法被多次引用,page/comment.php中调用此方法来记录客户端IP并将其带入数据库,代码如下
$submission_IP = $classes->getIP();
$_SQL = "INSERT INTO comments (content,submission_date,submission_IP)VALUES ('$COMMENT','$submission_date','$submission_IP');";
,这将造成X-Forwarded-For头注入,可通过恶意构造X-Forwarded-For头来造成sql注入

**Comment by EternalChampion61** [comment]
**接收到此Bug的警告后，我们将getIP函数进行了重构。**
function getIP()
    {
        $realIP = null;
        if (isset($_SERVER)) {
            if (isset($_SERVER["HTTP_X_FORWARDED_FOR"])) {
                $realIP = $_SERVER["HTTP_X_FORWARDED_FOR"];
            } else if (isset($_SERVER["HTTP_CLIENT_IP"])) {
                $realIP = $_SERVER["HTTP_CLIENT_IP"];
            } else {
                $realIP = $_SERVER["REMOTE_ADDR"];
            }
        }
        $isIPV4 = filter_var($realIP, FILTER_VALIDATE_IP);
        $isIPV6 = filter_var($realIP, FILTER_FLAG_IPV6);
        if ($isIPV4 || $isIPV6) {
            return $realIP;
        } else {
            die("<script>alert('XFF value is abnormal!');history.go(-1);</script>");
        }
    }
必须满足$isIPV4和$isIPV6其中一个变量为true才会返回地址，否则回到上一个历史页面。

**Comment by EternalChampion61** [comment]
Bug已修复。
